vector1=np.array([1,2])
vector2=np.array([1,3])
addition=np.add(vector1,vector2)
subtraction=np.subtract(vector2,vector1)
multiply=np.multiply(vector1,vector2)
divide=np.divide(vector1,vector2)
print(" added vectors are"+str(addition))
print(" subtracted vectors are"+str(subtraction))
print(" multiplication of vectors are"+str(multiply))
print("division of vectors are"+str(divide))
dotproduct=np.dot(vector1,vector2)
print("dot product is "+str(dotproduct))
vector=np.array([5,7])
scalar=np.array([3])
vector_scalar_mul=np.multiply(vector,scalar)
print(" result for vector scalar multiplication is "+str(vector_scalar_mul))