list=[21,2,3,45,56,67,8,2]
print("sorted list is :\n")
print(list)
print("reversed list is :\n")
list.reverse()
print(list)
list.reverse()
print("performing  slicing\n")
print(list[0:7])
print("performing  slicing with skip elements by 1 pos\n")
print(list[0:7:2])
print("length of the list\n")
len=len(list)
print(len)