# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tX0zr8hyH8OjY4HzQOhk_axNx8n1v0ru
"""

import numpy as n
two_digit_number = input()
fst=int(two_digit_number[0])
snd=int(two_digit_number[1])
print(fst+snd)

# 🚨 Don't change the code above 👆
####################################
# Write your code below this line 👇