# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tX0zr8hyH8OjY4HzQOhk_axNx8n1v0ru
"""

# Provide any name in the input pane below.
# That value can be accessed using the input() function.
# Don't put anything inside the input() function!
name=input()
count=0
for i in name:
  count=count+1
print(count)