# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tX0zr8hyH8OjY4HzQOhk_axNx8n1v0ru
"""

# Which year do you want to check?
year = int(input())
# 🚨 Don't change the code above 👆
if year % 4==0:
   print("Leap year")
else:
   print("Not leap year")


# Write your code below this line 👇