# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tX0zr8hyH8OjY4HzQOhk_axNx8n1v0ru
"""

# Which number do you want to check?
number = int(input())
# 🚨 Don't change the code above 👆
if number%2==0:
  print("This is an even number.")
else :
  print("This is an odd number.")

# Write your code below this line 👇