# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tX0zr8hyH8OjY4HzQOhk_axNx8n1v0ru
"""

print('''
*******************************************************************************
          |                   |                  |                     |
 _________|________________.=""_;=.______________|_____________________|_______
|                   |  ,-"_,=""     `"=.|                  |
|___________________|__"=._o`"-._        `"=.______________|___________________
          |                `"=._o`"=._      _`"=._                     |
 _________|_____________________:=._o "=._."_.-="'"=.__________________|_______
|                   |    __.--" , ; `"=._o." ,-"""-._ ".   |
|___________________|_._"  ,. .` ` `` ,  `"-._"-._   ". '__|___________________
          |           |o`"=._` , "` `; .". ,  "-._"-._; ;              |
 _________|___________| ;`-.o`"=._; ." ` '`."\` . "-._ /_______________|_______
|                   | |o;    `"-.o`"=._``  '` " ,__.--o;   |
|___________________|_| ;     (#) `-.o `"=.`_.--"_o.-; ;___|___________________
____/______/______/___|o;._    "      `".o|o_.--"    ;o;____/______/______/____
/______/______/______/_"=._o--._        ; | ;        ; ;/______/______/______/_
____/______/______/______/__"=._o--._   ;o|o;     _._;o;____/______/______/____
/______/______/______/______/____"=._o._; | ;_.--"o.--"_/______/______/______/_
____/______/______/______/______/_____"=.o|o_.--""___/______/______/______/____
/______/______/______/______/______/______/______/______/______/______/[TomekK]
*******************************************************************************
''')
print("WELCOME TO TREASURE ISLAND !!!!")
print("Hey there your mission is to find the treasure !! GOOD LUCK" )
choice1 = input("You are at a crossroad, and there are 2 ways left and right in front of you. Now, where will you go? (Type 'l' for left and 'r' for right)").lower()

if choice1 == 'l':
    choice2 = input("You have reached the water lake. What do you want to do, wait or swim to the island in front? (Use 'w' for wait and 's' for swim)").lower()

    if choice2 == 'w':
        print("You died of hunger. Game over!")
    elif choice2 == 's':
        print("You reached two doors.")
        choice3 = input("Which door would you like to open, red or blue? (Use 'R' for red and 'B' for blue)")

        if choice3 == 'r':
            print("Hooray! You found the treasure. You win!")
        else:
            print("Oops, you are petrified! Game over.")
    else:
        print("Invalid input. Game over!")

else:
    print("GAME OVER! You are eaten by a steel dragon. Try again!")