# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tX0zr8hyH8OjY4HzQOhk_axNx8n1v0ru
"""

print("Day 1 - Python Print Function")
print("The function is declared like this:")
print("print('what to print')")