# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NVP9752cVZ5LlpT9qyFdLt_fyF-qyw-X
"""

print("---------------------------")
print("Welcome to the tip calculator")
print("---------------------------")
print("What was the total bill?")
total_bill = float(input())
print("What percentage of tip would you like to give? (10, 12, or 15):")
tip_percentage = int(input())
print("How many people are in your group?")
num_people = int(input())

if tip_percentage == 10:
    tip_amount = total_bill * 0.10
elif tip_percentage == 12:
    tip_amount = total_bill * 0.12
elif tip_percentage == 15:
    tip_amount = total_bill * 0.15
else:
    print("Invalid tip percentage. Please choose from 10, 12, or 15.")
    exit()

total_amount = total_bill + tip_amount

amount_per_person = total_amount / num_people

print(f"Each person should pay: ${amount_per_person:.2f}")