# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15wkyXx2w8TQvAPxYmQSRx39reuRvehKC
"""

#check prime or not
num=int(input("enter num"))
prime=True
for i in range(2,num):
  if num%i==0:
    prime=False

if prime:
  print(f"{num} is true to be prime")
else:
  print(f"not true")